# Generated by Django 5.1.5 on 2025-02-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gender_alter_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
