# Generated by Django 6.0 on 2026-01-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_num', models.BigAutoField(default=700220000001, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.PositiveBigIntegerField(unique=True)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('aadhar', models.PositiveBigIntegerField(unique=True)),
                ('pan', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='photos')),
                ('address', models.TextField()),
                ('pin', models.CharField(default=0, max_length=64)),
                ('bal', models.IntegerField(default=1000)),
                ('nominee', models.CharField(max_length=100)),
                ('nominee_phone', models.PositiveBigIntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gender')),
                ('nominee_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.relationship')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
    ]
