# Generated by Django 6.0 on 2026-01-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_num',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
